// <auto-generated />
using HelloSchool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelloSchool.Migrations
{
    [DbContext(typeof(PreRegistroContext))]
    [Migration("20190729180437_PrimeraM")]
    partial class PrimeraM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelloSchool.Models.PreRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<string>("ApellidosEstudiante");

                    b.Property<string>("Celular");

                    b.Property<string>("Correo");

                    b.Property<bool>("Estado");

                    b.Property<int>("FechaNacimientoEstudiante");

                    b.Property<string>("NoDocumento");

                    b.Property<string>("NoDocumentoEstudiante");

                    b.Property<string>("Nombres");

                    b.Property<string>("NombresEstudiante");

                    b.Property<string>("Parentesco");

                    b.Property<string>("TipoDocumento");

                    b.Property<string>("TipoDocumentoEstudiante");

                    b.HasKey("Id");

                    b.ToTable("PreRegistros");
                });
#pragma warning restore 612, 618
        }
    }
}
